---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - databasus.databasus.io
  resources:
  - databasebackups
  - notifiers
  - storages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - databasus.databasus.io
  resources:
  - databasebackups/finalizers
  - notifiers/finalizers
  - storages/finalizers
  verbs:
  - update
- apiGroups:
  - databasus.databasus.io
  resources:
  - databasebackups/status
  - notifiers/status
  - storages/status
  verbs:
  - get
  - patch
  - update
