apiVersion: databasus.databasus.io/v1alpha1
kind: DatabaseBackup
metadata:
  labels:
    app.kubernetes.io/name: databasus-operator
    app.kubernetes.io/managed-by: kustomize
  name: databasebackup-sample
spec:
  # TODO(user): Add fields here
