{{- if .Values.databasus.credentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.databasus.credentials.secretName }}
  {{- with .Values.databasus.credentials.secretNamespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "databasus-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  email: {{ required "databasus.credentials.email is required when credentials.create is true" .Values.databasus.credentials.email | quote }}
  password: {{ required "databasus.credentials.password is required when credentials.create is true" .Values.databasus.credentials.password | quote }}
{{- end }}
